### PR TITLE
build fix for ghc-8.6

### PR DESCRIPTION
**Pull request by tmcdonell**

### CODE REVIEW

**Comment by osa1** [comment]
Ping @vincenthz .

It'd be really helpful if we could merge this and push a new version on Hackage.

**Comment by NicolasDP** [comment]
Seems like a regression in GHC :-(

**Comment by RyanGlScott** [comment]
This isn't a regression. The fact that the `memory` on Hackage stopped building with GHC 8.6.1 is a consequence of the new `StarIsType` extension (on by default) which substantially simplifies the treatment of `*` (as a synonym for `Type`) in GHC's parser, at the expense of requiring users to be explicit when using `*` as a binary type operator. See [the GHC 8.6 Migration Guide](https://ghc.haskell.org/trac/ghc/wiki/Migration/8.6?version=14#StarIsType) for the full story.

**Comment by DanBurton** [comment]
Thanks for merging this! Is the code in a good state to be uploaded to hackage as `memory-0.14.17`?

**Pull request merged**
