### PR TITLE
Add support for Haiku.

### PR DESCRIPTION
**Pull request by jessicah**

### CODE REVIEW

**Comment by jessicah** [comment]
I need to update this to also handle the call to madvise(), so not quite ready yet.

**Comment by jessicah** [comment]
Have updated PR, splitting out the POSIX madvise[1] checks from the Haiku checks.

[1] http://linux.die.net/man/3/posix_madvise

**Comment by vincenthz** [comment]
Otherwise, cool. I didn't know anyone was using Haskell on Haiku.

**Comment by jessicah** [comment]
Okay, that makes sense, will update as suggested :)

I've only just managed to properly package GHC the last couple days. This cropped up whilst trying to install pandoc :)

**Comment by jessicah** [comment]
PR updated :)

**Comment by jessicah** [comment]
Okay, fixed typo, and actually ran the build this time :P Fixed compilation errors too... hopefully it's now good to go ;-)

**Comment by jessicah** [comment]
FYI, I've done git push --force, so previous incarnations have been replaced by the updated commit.

**Comment by vincenthz** [comment]
Excellent. Thanks

**Pull request merged**
